name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip and install dependencies
        run: |
          python -m venv env
          . env/bin/activate  # Activa el entorno virtual
          python -m pip install --upgrade pip
          # Instala las dependencias desde el nuevo requirements.txt
          pip install -r requirements.txt
          # Verifica que el plugin esté instalado en el entorno virtual
          pip show mkdocs-static-i18n

      - name: Extract translations
        run: |
          . env/bin/activate
          # Construye el sitio sin --clean para mantener archivos generados (como .po)
          mkdocs build
          # Esto debería crear los archivos .po en la carpeta 'locale'

      - name: List translation files
        run: |
          . env/bin/activate
          ls -R locale  # Listar archivos para verificar si los .po están presentes

      - name: Verificar archivos .po
        run: |
          . env/bin/activate
          find locale -type f -name "*.po" || echo "No se encontraron archivos .po"

      - name: Upload PO files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: locale_files
          path: locale/**/*.po  # Subir todos los archivos .po de la carpeta locale como artefactos

      - name: Build translated site
        run: |
          . env/bin/activate
          mkdocs build --dirty  # Construir el sitio con las traducciones

      - name: Deploy to GitHub Pages
        run: |
          . env/bin/activate
          mkdocs gh-deploy --force
