name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocs-static-i18n transifex-client

      - name: Extract translations
        run: |
          # Run MkDocs with the i18n plugin to generate .pot files
          mkdocs build --dirtyreload
          # This will create .pot files in the 'locales' folder

      - name: Prepare Transifex configuration
        run: |
          tx init --skipsetup
          echo "[main]\nhost = https://www.transifex.com\n" > ~/.transifexrc
          # Add your Transifex project and settings here
          echo -e "[geonode_cloud_documentation]\nlang_map = es:es,en:en\ntype = PO" > .tx/config

      - name: Push source content to Transifex
        run: tx push -s  # Push source .pot files to Transifex

      - name: Pull translations from Transifex
        run: tx pull -a  # Pull all translations

      - name: Build translated site
        run: |
          mkdocs build --clean  # Build the site with translations

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
