name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip and install dependencies
        run: |
          python -m venv env
          . env/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip show mkdocs-static-i18n

      - name: Create locale directory
        run: mkdir -p locale  # Crea la carpeta si no existe

      - name: Extract translations
        run: |
          . env/bin/activate
          mkdocs build
          echo "Archivos generados en 'locale':"
          ls -R locale || echo "No se generaron archivos en la carpeta locale"

      - name: Verificar archivos .po
        run: |
          . env/bin/activate
          find locale -type f -name "*.po" || echo "No se encontraron archivos .po en locale"

      - name: Upload PO files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: locale_files
          path: locale/**/*.po  # Subir todos los archivos .po de la carpeta locale como artefactos

      - name: Build translated site
        run: |
          . env/bin/activate
          mkdocs build --dirty

      - name: Deploy to GitHub Pages
        run: |
          . env/bin/activate
          mkdocs gh-deploy --force
