name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install mkdocs-static-i18n
          pip install transifex-client

      - name: Extract translations
        run: |
          # Run MkDocs with the i18n plugin to generate .pot files
          mkdocs build --clean
          # Esto creará los archivos .pot en la carpeta 'locales'

      - name: Prepare Transifex configuration
        run: |
          tx init --skipsetup
          echo "[main]\nhost = https://www.transifex.com\n" > ~/.transifexrc
          # Agrega la configuración de tu proyecto Transifex aquí
          echo -e "[geonode_cloud_documentation]\nlang_map = es:es,en:en\ntype = PO" > .tx/config

      - name: Push source content to Transifex
        run: tx push -s  # Subir archivos .pot a Transifex

      - name: Pull translations from Transifex
        run: tx pull -a  # Descargar todas las traducciones

      - name: Build translated site
        run: |
          mkdocs build --clean  # Construir el sitio con las traducciones

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
