name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip and install dependencies
        run: |
          python3 -m venv env
          # Activa el entorno virtual
          . env/bin/activate
          python3 -m pip install --upgrade pip
          # Instala las dependencias en el entorno virtual
          pip install mkdocs==1.4.3 mkdocs-material==9.1.16
          pip install mkdocs-static-i18n==1.2.3
          pip install transifex-client
          # Verifica que el plugin esté instalado en el entorno virtual
          pip show mkdocs-static-i18n

      - name: Extract translations
        run: |
          # Ejecuta el comando dentro del entorno virtual
          . env/bin/activate
          mkdocs build --clean
          # Esto debería crear los archivos .pot en la carpeta 'locales'

      - name: Prepare Transifex configuration
        run: |
          . env/bin/activate
          tx init --skipsetup
          echo "[main]\nhost = https://www.transifex.com\n" > ~/.transifexrc
          # Configura el archivo Transifex
          echo -e "[geonode_cloud_documentation]\nlang_map = es:es,en:en\ntype = PO" > .tx/config

      - name: Push source content to Transifex
        run: |
          . env/bin/activate
          tx push -s  # Subir archivos .pot a Transifex

      - name: Pull translations from Transifex
        run: |
          . env/bin/activate
          tx pull -a  # Descargar todas las traducciones

      - name: Build translated site
        run: |
          . env/bin/activate
          mkdocs build --clean  # Construir el sitio con las traducciones

      - name: Deploy to GitHub Pages
        run: |
          . env/bin/activate
          mkdocs gh-deploy --force
